// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSGh6tNWsK61ObRa9xBkB69b8QD1KbAqo',
    appId: '1:814029138881:android:b6e9b60db3f2e4bf111d40',
    messagingSenderId: '814029138881',
    projectId: 'hchat-44f50',
    databaseURL: 'https://hchat-44f50-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hchat-44f50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr5R95BqWTR9qncw79KwW61zAza-jEwoE',
    appId: '1:814029138881:ios:b6c5cb3b8e80f7ca111d40',
    messagingSenderId: '814029138881',
    projectId: 'hchat-44f50',
    databaseURL: 'https://hchat-44f50-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hchat-44f50.appspot.com',
    androidClientId: '814029138881-3rl0878b0d68dbqhofen4dlntku42503.apps.googleusercontent.com',
    iosClientId: '814029138881-pk2msqufdpfepdahmn8ikc342gsc3quu.apps.googleusercontent.com',
    iosBundleId: 'com.bits.bitlogicx.bits',
  );
}
